### ISSUE TITLE
Functions are not functions?

### ISSUE THREAD

**Issue by PAK90** [zposten/jest-tsd#8]
I have a file named `index.test-d.ts`, and I've imported one of the sample tests:

```
test('Adding two numbers should produce a number', () => {
  expectType<number>(1 + 1);
  expectType<number>(2 + 2);
});
```

When I run this test in Webstorm IDE, it fails, saying the function `expectType` is not a function.

```
(0 , jest_tsd_1.expectType) is not a function
TypeError: (0 , jest_tsd_1.expectType) is not a function
```

I followed the installation procedure; I installed `jest-tsd` as well as `@tsd/typescript` as devDependencies, but no luck.

**Comment by 0livare** [comment]
Hi @PAK90,

Unfortunately I don't have much experience with the Webstorm IDE or its quirks. Does it work when you run `jest` from the command line directly? 

Also, any chance you're missing the import of `import {expectType} from 'jest-tsd'` in your type definition test?

**Comment by 0livare** [comment]
Also, just to be clear, you have two files that look like this, right?
(I would expect this setup to be working, so just making sure we're on the same page)

1. A type definition test file:
```ts
// index.test-d.ts

import { expectType } from 'jest-tsd'

test('Adding two numbers should produce a number', () => {
  expectType<number>(1 + 1)
  expectType<number>(2 + 2)
})
```

2. And a standard jest file:
```js
// index.test.js

import {expectTypeTestsToPassAsync} from 'jest-tsd'

it('should not produce static type errors', async () => {
  await expectTypeTestsToPassAsync(__filename)
})
```
